var keyMirror = require('keymirror');

var InsightConstants = keyMirror({
	RESIZE_APP: null,
	CONTROL_PANEL_VISIBLE: null,
	SELECT_DS_INDEX: null,
	FIND_MATCH: null,
	SELECT_QUERY: null,
	LOAD_QUERY: null,
	SELECT_DISTANCE: null,
	SELECT_THRESHOLD: null,
	SELECT_START_Q: null,
	SELECT_END_Q: null,
	REQUEST_DATA_INIT: null,
	VIEW_MODE_SIMILARITY: null,
	VIEW_MODE_SEASONAL: null,
	VIEW_MODE_CLUSTER: null,
	SELECT_QUERY_FROMDATASET: null,
	QUERY_TYPE_DATASET: null,
	QUERY_TYPE_UPLOAD: null,
	ICON_DATASET_INIT_LOADING: null,
	ICON_DATASET_INIT_LOADED: null,
	ICON_DATASET_INIT_NULL: null,
	GRAPH_TYPE_LINE: null,
	GRAPH_TYPE_HORIZON: null,
	GRAPH_TYPE_CONNECTED: null,
	GRAPH_TYPE_ERROR: null,
	GRAPH_TYPE_WARP: null,
	SELECT_DTW_BIAS: null,

	SEASONAL_SELECT_QUERY: null,
	SEASONAL_SELECT_LENGTH: null,
	SEASONAL_SELECT_PATTERN_INDEX: null,
	SEASONAL_REQUEST: null
});

module.exports = InsightConstants;
